### ISSUE TITLE
Zescrape'ować bazę wiedzy SGGW i wrzucić informacje do tabel bazy

### ISSUE THREAD

**Issue by Nixx-K** [IO-Lab2/Scraper#2]

**Comment by Nixx-K** [comment]
@KluskaGit Nie musisz scrapować SNIPu ani CiteScore widocznych w profilach. Co do h-indexów, potrzebujemy obu, WoS oraz Scopus. Zaraz oba pola zostaną dodane do bazy danych.

**Comment by Nixx-K** [comment]
@KluskaGit Co do publikacji, uważam, że do tabeli publications łatwiej będzie Ci scrapować stąd: https://bw.sggw.edu.pl/globalResultList.seam?r=publication&tab=PUBLICATION&lang=pl, a do tabeli scientists z profilu danego naukowca.

**Comment by KluskaGit** [comment]
> @KluskaGit Co do publikacji, uważam, że do tabeli publications łatwiej będzie Ci scrapować stąd: https://bw.sggw.edu.pl/globalResultList.seam?r=publication&tab=PUBLICATION&lang=pl, a do tabeli scientists z profilu danego naukowca.

Tabela scientists nie ma publikacji i wydaje mi się, że nie ma sensu scrapować z dwóch różnych źródeł tych samych informacji

**Comment by Nixx-K** [comment]
W takim razie uważam, że najłatwiej będzie Ci scrapować stąd: https://bw.sggw.edu.pl/globalResultList.seam?r=publication&tab=PUBLICATION&lang=pl.

**Comment by KluskaGit** [comment]
Na ten moment scraper jest w stanie pobrać prawie wszystkie informacje. Problem jest z tym, że muszę dostosować odpowiednią ilość requestów i opóźnienia bo inaczej dostanę error 500. Dodatkowo w profilu naukowca ministerial score jest generowany w inny sposób i nie zawsze jest pobierany. Dzisiaj powinienem dodać kilkuset naukowców z bibliometrią aby cokolwiek było w bazie i będę próbował ogarnąć resztę tabel w bazie aby coś zawierały. Też muszę się zastanowić nad schematem pobierania danych aby nie przeciążyć serwerów, gdyż ilość danych jest duża

**Comment by Nixx-K** [comment]
Dziękuję!

**Comment by KluskaGit** [comment]
Aktualnie wszystkie tabele posiadają dane, jedynie tabele publications i scientists_publications nie są w pełni wypełnione. Zostało mi tylko ogarnąć kolejność dodawania danych do bazy, wprowadzenie aktualizowania tabel i sprawdzenie czy scraper w pełni działa.

**Comment by KluskaGit** [comment]
Mały problem z publikacjami wyszedł bo się okazało że publikacje mają te same tytuły ze względu na to że zostały wydane w kilku częściach/tomach ale poradzę sobie z tym. Muszę jeszcze dodać opcję sprawdzenia czy publikacja jest w bazie i w zależności od tego ją dodawać. No i zapewne rozbiję tego spidera na dwa, jeden do naukowców a drugi do publikacji. W międzyczasie w bazie ma się pojawić nowa tabela, którą też muszę uzupełnić. No i zostaje poprawienie skalowalności tego wszystkiego.

**Comment by Nixx-K** [comment]
Dziękuję za informację.

**Comment by KluskaGit** [comment]
W bazie danych zostały wprowadzone drobne poprawki plus ta nowa tabela a więc uwzględniłem je i uzupełniłem tabele. Po kilku tysiącach requestów scraper się wykrzacza, co muszę naprawić. No i jeszcze nie rozbiłem go na dwa oddzielne spidery.

**Comment by Nixx-K** [comment]
Dziękuję!

**Comment by KluskaGit** [comment]
Problem się pojawił bo w ostatnim czasi, nie wiem kiedy ale jakoś nie dawno zmienił się layout strony dla naukowców przez co scraper się wysypał. Trzeba będzie poprawić pobieranie kilku pól.

**Comment by KluskaGit** [comment]
Poprawiłem już scraper o tą zmianę layoutu i działa, nawet udało mi się go przyspieszyć. Na ten moment uruchomiłem go tak aby po wszystkim przeszedł i zdażają się jakieś błędy i będę musiał je poprawić.

**Comment by Nixx-K** [comment]
Dziękuję!
